# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :dis do
    # add actions here: https://docs.fastlane.tools/actions
  gym(
    configuration: "Release",
    scheme: "KKPodImageTest_Example",
    export_method: 'enterprise',
    output_name: "KKPodImageTest_Distribution.ipa" ,
    )
  end
end
